#pragma once

#define ENABLE_JUSTIFY          1
#define ENABLE_NANORC           1
#define ENABLE_MOUSE            1
#define ENABLE_LINENUMBERS      1
#define ENABLE_LINTER           1
#define ENABLE_COLOR            1
#define HAVE_USE_DEFAULT_COLORS 1
#define PACKAGE                 "not-nano"
#define PACKAGE_STRING          "Not Nano v0.0.1"
#define PACKAGE_VERSION         "0.0.1"
#define VERSION                 "0.0.1"
#define PKGDATADIR              "/usr/local/share/nano"
#define PROMOTED_MODE_T         mode_t
#define ENABLE_WRAPPING         1
#define ENABLE_UTF8             1
#define ENABLE_EXTRA            1
#define ENABLE_FORMATTER        1
#define ENABLE_COMMENT          1
#define ENABLE_BROWSER          1
#define ENABLE_SPELL            1
#define ENABLE_MULTIBUFFER      1
#define ENABLE_HISTORIES        1
#define ENABLE_BOOKMARKS        1
#define ENABLE_HELP             1
#define ENABLE_OPERATINGDIR     1
#define ENABLE_TABCOMP          1
#define ENABLE_SPELLING         1
#define ENABLE_NLS              1
#define HAVE_LIBINTL_H          1
#define HAVE_MAGIC_H            1
#define HAVE_LIBMAGIC           1
#define ENABLE_WORDCOMPLETION   1
#define LOCALEDIR               "/usr/share/locale"
#define ENABLE_SPELLER          1
#define HAVE_KEY_DEFINED        1
#define HAVE_CHMOD              1
#define HAVE_CHOWN              1
